name: alt_point_components
description: AltPoint components lib.
version: 0.0.1
homepage: https://github.com/vinnikpuhh/alt_point_components

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.alt.point.alt_point_components
        pluginClass: AltPointComponentsPlugin
      ios:
        pluginClass: AltPointComponentsPlugin
